### PR TITLE
Sync with community and update to latest release

### PR DESCRIPTION
**Pull request by juangon**
Used ER6 instead of ER5 in this case

### CODE REVIEW

**Comment by Ladicek** [comment]
Needs an update to CR3.

**Comment by juangon** [comment]
@Ladicek done, good catch!

**Comment by Ladicek** [comment]
Great, thanks!

**Comment by Ladicek** [comment]
Just for tracking, removal of `@CreateSwarm` is covered by ENTSWM-530.

**Review by Ladicek — APPROVED** [review]

**Pull request merged**
